--
-- PostgreSQL database dump
--

\restrict a2e0SmnAODna2WfRhnNqrZRhE2LHtY0algmowQezWhRLyYRzHgo4Pd7e1jkgEXX

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    quantity integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.cart_items OWNER TO postgres;

--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    product_name character varying(120) NOT NULL,
    product_sku character varying(64),
    product_id bigint,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    order_number character varying(32) NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    shipping_address_id bigint,
    shipping_city character varying(64),
    shipping_district character varying(64),
    shipping_phone character varying(20),
    shipping_postal_code character varying(16),
    shipping_province character varying(64),
    shipping_recipient character varying(64),
    shipping_street character varying(128),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_PAYMENT'::character varying, 'PAID'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(120) NOT NULL,
    price numeric(10,2) NOT NULL,
    sku character varying(64) NOT NULL,
    status character varying(16) NOT NULL,
    stock integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    category character varying(60) DEFAULT '未分类'::character varying NOT NULL,
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_accounts (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(120) NOT NULL,
    password_hash character varying(120) NOT NULL,
    phone character varying(20),
    role character varying(16) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    username character varying(64) NOT NULL,
    CONSTRAINT user_accounts_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'CUSTOMER'::character varying])::text[])))
);


ALTER TABLE public.user_accounts OWNER TO postgres;

--
-- Name: user_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_addresses (
    id bigint NOT NULL,
    city character varying(64) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    district character varying(64) NOT NULL,
    is_default boolean NOT NULL,
    phone character varying(20) NOT NULL,
    postal_code character varying(16),
    province character varying(64) NOT NULL,
    recipient_name character varying(64) NOT NULL,
    street character varying(128) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_addresses OWNER TO postgres;

--
-- Name: user_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cart_items (id, created_at, quantity, updated_at, user_id, product_id) FROM stdin;
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (id, product_name, product_sku, product_id, quantity, unit_price, order_id) FROM stdin;
1	星辰蓝牙耳机	SC-AIR-01	1	1	299.00	1
2	极光智能手表	SC-WATCH-01	2	1	699.00	2
3	轻羽保温杯	SC-CUP-01	3	1	289.00	2
4	极光智能手表	SC-WATCH-01	2	4	699.00	77
5	星辰蓝牙耳机	SC-AIR-01	1	2	299.00	77
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, created_at, order_number, status, total_amount, updated_at, user_id, shipping_address_id, shipping_city, shipping_district, shipping_phone, shipping_postal_code, shipping_province, shipping_recipient, shipping_street) FROM stdin;
1	2025-11-10 09:49:17.512557+08	ORD-202511-0001	PAID	299.00	2025-11-10 09:49:17.512557+08	2	\N	\N	\N	\N	\N	\N	\N	\N
2	2025-11-10 09:49:17.515098+08	ORD-202511-0002	PAID	987.99	2025-11-10 22:27:44.911572+08	2	\N	\N	\N	\N	\N	\N	\N	\N
77	2025-11-11 15:23:10.9352+08	ORD-20251111152310-6967	PAID	3394.00	2025-11-11 15:27:54.737946+08	51	3	1	1	15727531930	150001	1	罗星宇	1
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, created_at, name, price, sku, status, stock, updated_at, category) FROM stdin;
3	2025-11-10 09:49:17.508972+08	轻羽保温杯	89.00	SC-CUP-01	INACTIVE	300	2025-11-10 09:49:17.508972+08	未分类
19	2025-11-10 16:35:37.728705+08	111	0.01	111	DRAFT	1	2025-11-10 16:35:37.728705+08	未分类
56	2025-11-10 20:58:18.533078+08	222	0.04	444	ACTIVE	2	2025-11-11 14:28:20.393828+08	未分类
57	2025-11-10 23:17:58.226718+08	士大夫但是	223.00	112	ACTIVE	1	2025-11-11 14:28:26.785335+08	未分类
2	2025-11-10 09:49:17.508972+08	极光智能手表	699.00	SC-WATCH-01	ACTIVE	76	2025-11-11 15:23:10.990325+08	未分类
1	2025-11-10 09:49:17.508972+08	星辰蓝牙耳机	299.00	SC-AIR-01	ACTIVE	118	2025-11-11 15:23:10.997327+08	未分类
118	2025-11-11 17:49:41.820138+08	12	111.00	311	ACTIVE	5	2025-11-11 17:49:41.820138+08	环境更加
119	2025-11-11 17:50:18.304754+08	会更加	15.00	12111	ACTIVE	11	2025-11-11 17:50:18.304754+08	你们
120	2025-11-11 17:51:08.705234+08	户口挂靠吗	543.00	2341354	ACTIVE	2432	2025-11-11 17:51:08.705234+08	66
121	2025-11-11 18:04:04.700634+08	耳机	250.00	1001	ACTIVE	9999	2025-11-11 18:04:04.700634+08	数码
122	2025-11-11 18:04:48.039692+08	机械革命	5000.00	66666	ACTIVE	999	2025-11-11 18:04:48.039692+08	电脑
123	2025-11-11 18:05:35.660386+08	老龙头	997.00	1002	ACTIVE	55	2025-11-11 18:05:35.660386+08	啥
124	2025-11-11 18:25:07.232471+08	麻辣王子	10.00	1003	ACTIVE	99	2025-11-11 18:25:07.232471+08	食品
125	2025-11-11 18:25:30.637899+08	伊利纯牛奶	48.00	1004	ACTIVE	99	2025-11-11 18:25:30.637899+08	食品
126	2025-11-11 18:26:06.01013+08	水杯	18.00	1005	ACTIVE	99	2025-11-11 18:26:06.01013+08	杂
\.


--
-- Data for Name: user_accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_accounts (id, active, created_at, email, password_hash, phone, role, updated_at, username) FROM stdin;
2	t	2025-11-08 12:02:57.226172+08	user01@example.com	{noop}user123	13900000001	CUSTOMER	2025-11-10 22:30:24.725865+08	user01
1	t	2025-11-08 12:02:57.223729+08	admin@example.com	{bcrypt}$2a$10$IxlyaMIX91pjTO8ldu4Hh.h4ZTvWJ6zHJLS1O9Z0fDfu2OxndMWIm	13800000000	ADMIN	2025-11-10 22:56:16.742062+08	admin
51	t	2025-11-10 23:40:34.406239+08	2932547376@qq.com	{bcrypt}$2a$10$2K3rDkcTxW3gWKjS7A9O3ek3/JSnU8xaWMwcO61LqFXEn/UhtddVm	15727531930	CUSTOMER	2025-11-11 00:17:18.044086+08	w2321
\.


--
-- Data for Name: user_addresses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_addresses (id, city, created_at, district, is_default, phone, postal_code, province, recipient_name, street, updated_at, user_id) FROM stdin;
1	广州市	2025-11-11 11:34:15.599737+08	天河区	t	13900000001	510000	广东省	张三	科韵路 99 号 星辰公寓 1 栋 502	2025-11-11 11:34:15.599737+08	2
2	深圳市	2025-11-11 11:34:15.602687+08	南山区	f	13900000002	518000	广东省	张三	科技园 创新大道 88 号 A 座 1203	2025-11-11 11:34:15.602687+08	2
3	1	2025-11-11 13:38:08.511919+08	1	t	15727531930	150001	1	罗星宇	1	2025-11-11 13:40:05.243831+08	51
4	2	2025-11-11 13:39:43.619906+08	2	f	15727531930	\N	的	发	的	2025-11-11 13:40:03.946762+08	51
\.


--
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 4, true);


--
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_items_id_seq', 5, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 77, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 126, true);


--
-- Name: user_accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_accounts_id_seq', 87, true);


--
-- Name: user_addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_addresses_id_seq', 4, true);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: cart_items uk_cart_user_product; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT uk_cart_user_product UNIQUE (user_id, product_id);


--
-- Name: user_accounts ukf9sl209luxhu4rylls0h1m625; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT ukf9sl209luxhu4rylls0h1m625 UNIQUE (email);


--
-- Name: products ukfhmd06dsmj6k0n90swsh8ie9g; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT ukfhmd06dsmj6k0n90swsh8ie9g UNIQUE (sku);


--
-- Name: user_accounts uklxwlgwuy2yrbye2vgs9w9x7mr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT uklxwlgwuy2yrbye2vgs9w9x7mr UNIQUE (username);


--
-- Name: orders uknthkiu7pgmnqnu86i2jyoe2v7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uknthkiu7pgmnqnu86i2jyoe2v7 UNIQUE (order_number);


--
-- Name: user_accounts user_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT user_accounts_pkey PRIMARY KEY (id);


--
-- Name: user_addresses user_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_addresses
    ADD CONSTRAINT user_addresses_pkey PRIMARY KEY (id);


--
-- Name: idx_user_addresses_default; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_addresses_default ON public.user_addresses USING btree (user_id, is_default);


--
-- Name: idx_user_addresses_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_addresses_user ON public.user_addresses USING btree (user_id);


--
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id);


-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: orders fkj155sw2aro8ofqiu74xhsvdqo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkj155sw2aro8ofqiu74xhsvdqo FOREIGN KEY (user_id) REFERENCES public.user_accounts(id);


--
-- Name: user_addresses fklpgrk68vmheqg6iawu8l20sb9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_addresses
    ADD CONSTRAINT fklpgrk68vmheqg6iawu8l20sb9 FOREIGN KEY (user_id) REFERENCES public.user_accounts(id);


--
-- PostgreSQL database dump complete
--

\unrestrict a2e0SmnAODna2WfRhnNqrZRhE2LHtY0algmowQezWhRLyYRzHgo4Pd7e1jkgEXX

