create table user_accounts (
    id bigint generated by default as identity primary key,
    active boolean not null,
    created_at timestamp with time zone not null,
    email varchar(120) not null,
    password_hash varchar(120) not null,
    phone varchar(20),
    role varchar(16) not null,
    updated_at timestamp with time zone not null,
    username varchar(64) not null
);

create table user_addresses (
    id bigint generated by default as identity primary key,
    city varchar(64) not null,
    created_at timestamp with time zone not null,
    district varchar(64) not null,
    is_default boolean not null,
    phone varchar(20) not null,
    postal_code varchar(16),
    province varchar(64) not null,
    recipient_name varchar(64) not null,
    street varchar(128) not null,
    updated_at timestamp with time zone not null,
    user_id bigint not null
);

create table products (
    id bigint generated by default as identity primary key,
    category varchar(60) not null,
    created_at timestamp with time zone not null,
    name varchar(120) not null,
    price numeric(10,2) not null,
    sku varchar(64) not null,
    status varchar(16) not null,
    stock integer not null,
    updated_at timestamp with time zone not null
);

create table cart_items (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    quantity integer not null,
    updated_at timestamp with time zone not null,
    user_id bigint not null,
    product_id bigint not null
);

create table orders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    order_number varchar(32) not null,
    status varchar(20) not null,
    total_amount numeric(10,2) not null,
    updated_at timestamp with time zone not null,
    user_id bigint not null,
    shipping_address_id bigint,
    shipping_city varchar(64),
    shipping_district varchar(64),
    shipping_phone varchar(20),
    shipping_postal_code varchar(16),
    shipping_province varchar(64),
    shipping_recipient varchar(64),
    shipping_street varchar(128)
);

create table order_items (
    id bigint generated by default as identity primary key,
    product_name varchar(120) not null,
    product_sku varchar(64),
    quantity integer not null,
    unit_price numeric(10,2) not null,
    order_id bigint not null
);
